
namespace AnkaYazilim.OnMuhasebe.DTOs.BankaSubeler;

public interface IBankaSubeAppService: AnkaYazilim.OnMuhasebe.Services.ICrudAppService<SelectBankaSubeDto,ListBankaSubeDto,BankaSubeListParameterDto,CreateBankaSubeDto,UpdateBankaSubeDto,BankaSubeCodeParametreDto>
{
}
